### ISSUE TITLE
course MITx/8.MReVx/2T2014 passes tests but fails to load

### ISSUE THREAD

**Issue by pdpinch** [mitodl/openedx-course-test#20]
Not sure how interesting a case this is, but let me know if you want the tarball.

Excerpted output:

> XML Syntax Check Successful

...

> JSON Syntax Check Successful

...

> Starting Course Import
> /test_course
> Traceback (most recent call last):
>  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
>    "__main__", fname, loader, pkg_name)
>  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
>    exec code in run_globals
>  File "/test_course/py_course_test/__main__.py", line 9, in <module>
>    import_course(sys.argv[1])
>  File "/test_course/py_course_test/import_test.py", line 46, in import_course
>    assert len(courses) == 1
> AssertionError

**Comment by carsongee** [comment]
I would be interested in the tarball, but this is an intentional test case to catch for our tester, and this is just a failure of the "import" test.  I would have hoped the import log before this assertion failure would have had more helpful information as it is full `DEBUG` level log output. Another possibility is that you have more than one course in the folder that is being tested, if that is the case `len(courses)` would be >1 and fail that assertion.

**Comment by pdpinch** [comment]
In [further discussion on ZenDesk](https://odl.zendesk.com/agent/tickets/1774), we realized this was caused by an exception raised by the policy file. 

I don't know why the error was more detailed in the server error logs than it was in the course import test. Is there additional debugging that needs to be turned on?

**Comment by carsongee** [comment]
The course test is based on the latest release of edX (with version two of expermients), so I'm guessing it got gummed up somewhere different the version number and that is why it was less helpful
